spring:
  datasource:
    orders:
      primary:
        jdbcUrl: jdbc:mysql://localhost:4406/orders?serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
        username: root
        password: 111
        driver-class-name: com.mysql.cj.jdbc.Driver
      secondary:
        jdbcUrl: jdbc:mysql://localhost:5506/orders?serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
        username: root
        password: 111
        driver-class-name: com.mysql.cj.jdbc.Driver
    products:
      url: jdbc:mysql://localhost:4406/products?serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      username: root
      password: 111
      driver-class-name: com.mysql.cj.jdbc.Driver
    users:
      url: jdbc:mysql://localhost:4406/users?serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      username: root
      password: 111
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
     primary:
       db: TRACE
     secondary:
       db: TRACE

