spring:
  datasource:
    orders:
      url: jdbc:shardingsphere:classpath:orders.yaml
      username: root
      password: 111
      driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    products:
      url: jdbc:mysql://localhost:4406/products?serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      username: root
      password: 111
      driver-class-name: com.mysql.cj.jdbc.Driver
    users:
      url: jdbc:mysql://localhost:4406/users?serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      username: root
      password: 111
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
