name: Sub Workflow

on:
  workflow_call:
    inputs:
      example_input:
        description: "An example input"
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show Input
        run: echo "Input received: ${{ github.event.inputs.example_input }}"